### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by ac-daman** [dzt/shopify-monitor#1]
Hey,
I did setup the config file, did all the setup things, but when I type node monitor.js on my terrminal 
[11:39:06] Missing, config.json file or invalid json syntax.

**Comment by dzt** [comment]
Run your config.json in a JSON Validator website like this one http://jsonlint.com/ <http://jsonlint.com/> and it should show you where the syntax error is

**Comment by ac-daman** [comment]
Ok, thanks, got that fixed but now i get

module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/alfonsocorona/monitor.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by ac-daman** [comment]
Ok, now i moved monitor.js to my home folder, as well as api.js, b/c i think that was the problem

now i get

module.js:472
    throw err;
    ^

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alfonsocorona/api.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by dzt** [comment]
You have the run 

npm install

As I instructed in the README

**Comment by ac-daman** [comment]
ok did that, then I'm ready for the monitor.js command?

**Comment by ajshaffer** [comment]
this is the error i get after moving api.js and monitor.js to my home folder

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/AustinShaffer/api.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Austins-MacBook-Pro:~ AustinShaffer$ npm install
npm WARN enoent ENOENT: no such file or directory, open '/Users/AustinShaffer/package.json'
npm WARN AustinShaffer No description
npm WARN AustinShaffer No repository field.
npm WARN AustinShaffer No README data
npm WARN AustinShaffer No license field.
Austins-MacBook-Pro:~ AustinShaffer$ git clone https://github.com/dzt/shopify-monitor.git
fatal: destination path 'shopify-monitor' already exists and is not an empty directory.
Austins-MacBook-Pro:~ AustinShaffer$ cd shopify-monitor
Austins-MacBook-Pro:shopify-monitor AustinShaffer$ npm install
npm WARN shopify-monitor@1.0.0 No repository field.
Austins-MacBook-Pro:shopify-monitor AustinShaffer$

**Comment by ajshaffer** [comment]
![screen shot 2017-01-17 at 11 03 50 am](https://cloud.githubusercontent.com/assets/19845347/22028265/b0c38042-dca4-11e6-84ee-77740ccbeacb.png)
No valid JSON response
