### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by ecomkings** [dzt/shopify-monitor#100]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle shopify-monitor-2@2.0.0~prestart: shopify-monitor-2@2.0.0
6 info lifecycle shopify-monitor-2@2.0.0~start: shopify-monitor-2@2.0.0
7 verbose lifecycle shopify-monitor-2@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle shopify-monitor-2@2.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Locals\Desktop\shopify-monitor-master\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Ruby23-x64\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Python27;C:\Python27\python.exe;C:\Users\Nitro Zeus\.dnx\bin;C:\python35\python35.exe;C:\Program Files\Microsoft DNX\Dnvm\;C:\python35\Scripts;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Python27\Scripts;C:\python35;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Skype\Phone\;C:\python35\Scripts\pip.exe;C:\Users\Locals\AppData\Local\Programs\Python\Python36-32\;C:\Users\Locals\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\xampp\php;C:\xampp\php\php.exe;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\ProgramData\chocolatey\bin;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\Locals\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Locals\AppData\Local\Programs\Python\Python36-32\;C:\Users\Locals\AppData\Local\Microsoft\WindowsApps;C:\python35\Scripts;C:\Users\Locals\AppData\Local\atom\bin;C:\Users\Locals\AppData\Roaming\npm
9 verbose lifecycle shopify-monitor-2@2.0.0~start: CWD: C:\Users\Locals\Desktop\shopify-monitor-master
10 silly lifecycle shopify-monitor-2@2.0.0~start: Args: [ '/d /s /c', 'babel-node index.js' ]
11 silly lifecycle shopify-monitor-2@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle shopify-monitor-2@2.0.0~start: Failed to exec start script
13 verbose stack Error: shopify-monitor-2@2.0.0 start: `babel-node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid shopify-monitor-2@2.0.0
15 verbose cwd C:\Users\Locals\Desktop\shopify-monitor-master
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error shopify-monitor-2@2.0.0 start: `babel-node index.js`
22 error Exit status 1
23 error Failed at the shopify-monitor-2@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ecomkings** [comment]
I have no idea what happen, it was working just fine and now all of a sudden it won't run ... can anyone see wha tmight be the issue?
