### ISSUE TITLE
TypeError: cannot read property 'loc' 

### ISSUE THREAD

**Issue by Zero-01010** [dzt/shopify-monitor#111]
hu Jan 25 2018 12:13:11] [ERROR] TypeError: Cannot read property 'loc' of undefined
    at persistentRun (/Users/dannyjess/shopify-monitor/service.js:175:57)
    at /Users/dannyjess/shopify-monitor/service.js:163:19
    at tryCatcher (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/dannyjess/shopify-monitor/node_modules/knex/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by Zero-01010** [comment]
Any way to fix this made to install all dependancies, but keep running into this error 2 minutes into running!
