### ISSUE TITLE
ReferenceError: stock is not defined

### ISSUE THREAD

**Issue by victorduruy** [dzt/shopify-monitor#117]
Getting this error on startup, no matter whether using Discord or Slack:

**Discord:**

ReferenceError: stock is not defined
    at DiscordWebhook.myWebhook.on (/home/ubuntu/shopify-monitor/src/classes/Notify.js:55:15)
    at DiscordWebhook.emit (events.js:180:13)
    at Request.DiscordWebhook.request [as _callback] (/home/ubuntu/shopify-monitor/node_modules/discord-webhooks/index.js:33:12)
    at Request.self.callback (/home/ubuntu/shopify-monitor/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/ubuntu/shopify-monitor/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/ubuntu/shopify-monitor/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
Emitted 'error' event at:
    at Request.DiscordWebhook.request [as _callback] (/home/ubuntu/shopify-monitor/node_modules/discord-webhooks/index.js:35:12)
    at Request.self.callback (/home/ubuntu/shopify-monitor/node_modules/request/request.js:186:22)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:178:19)

------
<img width="739" alt="screen shot 2018-04-28 at 2 28 45 pm" src="https://user-images.githubusercontent.com/8877933/39399876-f1585178-4af3-11e8-88b0-d1ee376ef5ae.png">

**Slack:**

[Sat Apr 28 2018 18:34:33] [LOG]   [undefeated.com]: Restock/Price Change: https://undefeated.com/products/kamanda-cblack-gum3
/home/ubuntu/shopify-monitor/src/classes/Notify.js:109
				  "value": stock,
				           ^

ReferenceError: stock is not defined
    at Object.Notify.slack (/home/ubuntu/shopify-monitor/src/classes/Notify.js:109:16)
    at Shopify.getStockData (/home/ubuntu/shopify-monitor/src/classes/Task.js:213:26)
    at Request._callback (/home/ubuntu/shopify-monitor/src/classes/Shopify.js:215:12)
    at Request.self.callback (/home/ubuntu/shopify-monitor/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/ubuntu/shopify-monitor/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/ubuntu/shopify-monitor/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)

Running Ubuntu 16.04 LTS, starting server with node server command.

**Comment by Lifinest7** [comment]
did u ever find a solution, or is iy down

**Comment by victorduruy** [comment]
None, happens on Windows as well.

**Comment by vanhoof** [comment]
This has stabilized things for me, I assume I'll lose any stock counts sent to the webhooks, unsure of any other ill effects, but the crashes have stopped and updates are being sent to my discord server

https://gist.github.com/vanhoof/0d98d50a17a9c4c1c3df11487c70f259
