### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by iptvship** [dzt/shopify-monitor#118]
`[Fri May 04 2018 08:07:24] [LOG]   [undefeated.com] Changes were made
[Fri May 04 2018 08:07:27] [LOG]   [undefeated.com]: Restock/Price Change: https://undefeated.com/products/undefeated-icon-tee
[Fri May 04 2018 08:07:27] [LOG]   { port: 3000,
  mongodb_uri: 'mongodb://127.0.0.1:27017',
  slack: { active: false, webhook_url: '' },
  discord:
   { active: 'checked',
     webhook_url: 'https://discordapp.com/api/webhooks/428567064068751371/owqGYZ7ciDP05z0kzwaQ3ooadi70nr2Np2vWsAx5krRyKmelJL1reUFQSdGBTjn231Ud' } }
events.js:183
      throw er; // Unhandled 'error' event
      ^

ReferenceError: stock is not defined
    at DiscordWebhook.myWebhook.on (C:\Users\Administrator\Desktop\shopify-monitor\src\classes\Notify.js:55:15)
    at emitNone (events.js:106:13)
    at DiscordWebhook.emit (events.js:208:7)
    at Request.DiscordWebhook.request [as _callback] (C:\Users\Administrator\Desktop\shopify-monitor\node_modules\discord-webhooks\index.js:33:12)
    at Request.self.callback (C:\Users\Administrator\Desktop\shopify-monitor\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Administrator\Desktop\shopify-monitor\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Desktop\shopify-monitor\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)`

**Comment by victorduruy** [comment]
Same error I'm getting across Windows or Linux.

**Comment by iptvship** [comment]
yes i been getting this on new update

**Comment by vanhoof** [comment]
This seems to have stabilized things for me, I assume the result will be no stock will be passed to a webhook, but no crashes like before:

diff --git a/src/classes/Notify.js b/src/classes/Notify.js
index 0220806..94283cd 100644
--- a/src/classes/Notify.js
+++ b/src/classes/Notify.js
@@ -50,10 +50,10 @@ Notify.discord = function (webhook_url, url, brand, metadata, type, color) {
                                        "name": "Notification Type",
                                        "value": type,
                                        "inline": true
-                               }, {
-                                       "name": "Stock Count",
-                                       "value": stock,
-                                       "inline": true
+                               //}, {
+                               //      "name": "Stock Count",
+                               //      "value": stock,
+                               //      "inline": true
                                }, {
                                        "name": "Brand",
                                        "value": brand,
@@ -179,4 +179,4 @@ Notify.ys = function (webhook_url, data) {
        });
 }

**Comment by vanhoof** [comment]
This has stabilized things for me, I assume I'll lose any stock counts sent to the webhooks, unsure of any other ill effects, but the crashes have stopped

`vanhoof@chinstrap:~/scratch/shopify-monitor$ git diff .
diff --git a/src/classes/Notify.js b/src/classes/Notify.js
index 0220806..94283cd 100644
--- a/src/classes/Notify.js
+++ b/src/classes/Notify.js
@@ -50,10 +50,10 @@ Notify.discord = function (webhook_url, url, brand, metadata, type, color) {
                                        "name": "Notification Type",
                                        "value": type,
                                        "inline": true
-                               }, {
-                                       "name": "Stock Count",
-                                       "value": stock,
-                                       "inline": true
+                               //}, {
+                               //      "name": "Stock Count",
+                               //      "value": stock,
+                               //      "inline": true
                                }, {
                                        "name": "Brand",
                                        "value": brand,
@@ -179,4 +179,4 @@ Notify.ys = function (webhook_url, data) {
        });
 }
`

**Comment by vanhoof** [comment]
This has stabilized things for me, I assume I'll lose any stock counts sent to the webhooks, unsure of any other ill effects, but the crashes have stopped

https://gist.github.com/vanhoof/0d98d50a17a9c4c1c3df11487c70f259

**Comment by shazam99** [comment]
got it solved. Download the Notify.js and swap your with this. http://www.mediafire.com/file/nott5ve6ai5ijww/Notify.js.zip
