### ISSUE TITLE
TypeError: Cannot read property 'img' of null

### ISSUE THREAD

**Issue by Semetix** [dzt/shopify-monitor#119]
image: res.img,

           ^

TypeError: Cannot read property 'img' of null
    at Shopify.getStockData (C:\Users\damanu2199\Desktop\shopify-monitor\src\classes\Task.js:133:27)
    at Request._callback (C:\Users\damanu2199\Desktop\shopify-monitor\src\classes\Shopify.js:218:12)
    at Request.self.callback (C:\Users\damanu2199\Desktop\shopify-monitor\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\damanu2199\Desktop\shopify-monitor\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\damanu2199\Desktop\shopify-monitor\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

How can I fix that ?

**Comment by shazam99** [comment]
same with me

**Comment by TaquitoSlayer** [comment]
yo peter stop emo tweeting and fix your shit

**Comment by FivePageGames** [comment]
Hi,
If you go to src\classes\Task.js and then rule: 133. You can remove the line.
It worked for me, and there have been no changes in the bot itself.
