### ISSUE TITLE
I keep getting this Syntax Error

### ISSUE THREAD

**Issue by glancing** [dzt/shopify-monitor#124]
SyntaxError: Unexpected token i in JSON at position 17
    at JSON.parse (<anonymous>)
    at formatJSON (C:\Users\Nathaniel Rubin\Desktop\shopify-monitor\src\classes\Shopify.js:118:15)
    at Object.Shopify.parseVariantsYS (C:\Users\Nathaniel Rubin\Desktop\shopify-monitor\src\classes\Shopify.js:144:24)
    at Request.request [as _callback] (C:\Users\Nathaniel Rubin\Desktop\shopify-monitor\src\classes\Shopify.js:76:12)
    at Request.self.callback (C:\Users\Nathaniel Rubin\Desktop\shopify-monitor\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Nathaniel Rubin\Desktop\shopify-monitor\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (C:\Users\Nathaniel Rubin\Desktop\shopify-monitor\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

When I start the monitor, I get this error and it stops working. How should I fix it.

**Comment by nrubin3** [comment]
[Sun Jun 24 2018 11:51:29] [ERROR] (node:16220) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnectio


I also get this error after typing node.server.
