### ISSUE TITLE
Node server.js Error

### ISSUE THREAD

**Issue by Hypify** [dzt/shopify-monitor#130]
node server.js
C:\Users\Censored\config:2
    "port": 3000,
          ^

SyntaxError: Unexpected token :
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Paul\Desktop\SneakLeakGroup\shopify-monitor\server.js:31:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

Got this every time i write "node server.js"

config:
{
    "port": 3000,
    "mongodb_uri": "mongodb://127.0.0.1:27017",
    "slack": {
        "active": false,
        "webhook_url": ""
    },
    "discord": {
        "active": false,
        "webhook_url": ""
    }
}

**Comment by Marcellone** [comment]
also for me

**Comment by OneRevlis** [comment]
same here
