### ISSUE TITLE
Node Server Error

### ISSUE THREAD

**Issue by zestyk** [dzt/shopify-monitor#156]
When I type in "node server" it shows:

λ node server
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\v\shopify-monitor\server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Appreciate it if anyone could help!

**Comment by Zomagoras** [comment]
To fix this follow the install video again, but use the below URL instead. He has the wrong URL in the read me. I would recommend just completely restarting it. This is what fixed it for me.

`git clone https://github.com/dzt/shopify-monitor.git`
