### ISSUE TITLE
Garbage collection is not exposed

### ISSUE THREAD

**Issue by ronmo32992** [dzt/shopify-monitor#27]
$ node monitor.js
Garbage collection is not exposed
C:\Users\user\Desktop\shopify-monitor\monitor.js:52
var a = configuration.keywords
                     ^

ReferenceError: configuration is not defined
    at Object.<anonymous> (C:\Users\user\Desktop\sitemon\shopify-monitor\monitor.js:52:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by cameronb23** [comment]
Closing due to inactivity, although this is in reference to an invalid reference in the code.
