### ISSUE TITLE
TypeError: res.links.join is not a function

### ISSUE THREAD

**Issue by KicksDNA** [dzt/shopify-monitor#28]
I get the following error after starting the program. It also seems as though the program tweets initial results because I start the program, it finds a bunch of matches, tweets a lot of them out, then crashes due to the following error. I have new and restocks set to false and keywords set to true. Should I set them all to false? Thank you.
 
           var links = res.links.join('\n')
                                  ^

TypeError: res.links.join is not a function
    at send (C:\Users\da_so\Desktop\shopify-monitor-master\shopify-monitor-master\monitor.js:408:35)
    at lib.getStockData (C:\Users\da_so\Desktop\shopify-monitor-master\shopify-monitor-master\monitor.js:396:13)
    at Request._callback (C:\Users\da_so\Desktop\shopify-monitor-master\shopify-monitor-master\lib\index.js:71:20)
    at self.callback (C:\Users\da_so\Desktop\shopify-monitor-master\shopify-monitor-master\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\da_so\Desktop\shopify-monitor-master\shopify-monitor-master\node_modules\request\request.js:845:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dzt** [comment]
This issue has been resolve in commit [e124d6d ](https://github.com/dzt/shopify-monitor/commit/075d658594580d8bd01516b0c2d6fbe00199fd9e).
