### ISSUE TITLE
var res.links.join is not a function

### ISSUE THREAD

**Issue by soleribbon** [dzt/shopify-monitor#36]
Having an issue after running the monitor for a while: 

var links = res.links.join('\n')
                                  ^

TypeError: res.links.join is not a function
    at send (/root/xbz123/monitor.js:408:35)
    at lib.getStockData (/root/xbz123/monitor.js:396:13)
    at Request._callback (/root/xbz123/lib/index.js:71:20)
    at self.callback (/root/xbz123/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/root/xbz123/node_modules/request/request.js:845:
8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zhibolau** [comment]
also got this

**Comment by Asteezy24** [comment]
same

**Comment by dzt** [comment]
I'll fix it when I have the time

**Comment by dzt** [comment]
This issue has been resolve in commit [e124d6d ](https://github.com/dzt/shopify-monitor/commit/075d658594580d8bd01516b0c2d6fbe00199fd9e).
