### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by cjlatch125** [dzt/shopify-monitor#4]
Hey, I got the monitor set up and it was working fine, but when I added a few new sites it started throwing this error.

/Users/c/shopify-monitor/lib/index.js:113
                    image: products[i].images[0].src,
                                                ^

TypeError: Cannot read property 'src' of undefined
    at Request._callback (/Users/c/shopify-monitor/lib/index.js:113:49)
    at Request.self.callback (/Users/c/shopify-monitor/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/c/shopify-monitor/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/c/shopify-monitor/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by dzt** [comment]
I'll look into it asap once I get home!

**Comment by cjlatch125** [comment]
Thanks
