### ISSUE TITLE
Node Monitor Wont Run

### ISSUE THREAD

**Issue by YeezySzn** [dzt/shopify-monitor#45]
YzySeason-Macbook-Pro:shopify-monitor yzyseason$ node monitor
/Users/yzyseason/Desktop/shopify-monitor/monitor.js:68
    let data = {
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by yourfavorite** [comment]
What version of node are you running? You shouldn't be getting this in v7.
To get around this I'd recommend upgrading node, if you don't want to do that (even though you should) try adding the following as the very first line in your monitor.js
'use strict';

**Comment by YeezySzn** [comment]
I am on 4.4.7

**Comment by YeezySzn** [comment]
I just upgraded to 7.7.3

**Comment by YeezySzn** [comment]
I changed config.example.json to config.json but I am getting the same this error

$ node monitor
Garbage collection is not exposed
[11:56:34] Missing, config.json file or invalid json syntax.

**Comment by YeezySzn** [comment]
YzySeason-Macbook-Pro:~ yzyseason$ cd desktop
YzySeason-Macbook-Pro:desktop yzyseason$ cd shopify-monitor
YzySeason-Macbook-Pro:shopify-monitor yzyseason$ npm install
YzySeason-Macbook-Pro:shopify-monitor yzyseason$ npm start

> shopify-monitor@1.0.0 start /Users/yzyseason/Desktop/shopify-monitor
> node --expose_gc monitor.js

[11:58:22] Missing, config.json file or invalid json syntax.
YzySeason-Macbook-Pro:shopify-monitor yzyseason$ node monitor
Garbage collection is not exposed
[11:58:33] Missing, config.json file or invalid json syntax.

**Comment by yourfavorite** [comment]
First you need to rename your computer :p
As for this error, if you renamed config.json you shouldn't be getting that error. Note that you should run npm start instead of monitor in order to avoid the GC is not exposed error.

From your shopify-monitor folder try running this command.
`test -e ./config.json && echo "YES" || echo "NO"`
If it says no, then you did something wrong. Either didn't rename the file properly or something. If it says yes, then I'm not sure why you'd be getting the error.

**Comment by YeezySzn** [comment]
Literally have no idea why it is not working

**Comment by yourfavorite** [comment]
You have invalid json syntax most likely since the file clearly exists.

Paste your config file into this site: http://jsonlint.com/

**Comment by YeezySzn** [comment]
So I put it in turns out I was missing a comma.  So I changed that and saved it still returns 

Missing, config.json file or invalid json syntax.

**Comment by yourfavorite** [comment]
Then there is another syntax error. I recommend downloading the default config file and re-editing in your info. As long as you are getting that error, you have a syntax error.

**Comment by YeezySzn** [comment]
YzySeason-Macbook-Pro:~ yzyseason $ node -v
v7.7.3
YzySeason-Macbook-Pro:~ yzyseason $ cd /Users/yzyseason/Desktop/shopify-monitor 
YzySeason-Macbook-Pro:shopify-monitor yzyseason $ npm install
YzySeason-Macbook-Pro:shopify-monitor yzyseason $ npm start

> shopify-monitor@1.0.0 start /Users/yzyseason/Desktop/shopify-monitor
> node --expose_gc monitor.js

[12:53:20] Missing, config.json file or invalid json syntax.
YzySeason-Macbook-Pro:shopify-monitor yzyseason $ node monitor
Garbage collection is not exposed
[12:53:23] Missing, config.json file or invalid json syntax.

**Comment by YeezySzn** [comment]
'use strict';
{
    "interval": 1000,
    "serverPort": 1337,
    "autoRetryOnCrash": true,
    "noImageURL": "http://i.imgur.com/MdsG0Po.png",
    "notify": {
        "new": true,
        "restocks": true,
        "keywords": true
    },
    "slackBot": {
        "active": false,
        "token": "token goes here",
        "channel": "monitor",
        "settings": {
            "username": "ShopifyMonitor",
            "icon_url": "http://i.imgur.com/zks3PoZ.png"
        }
    },
    "twitter": {
        "active": true,
        "encodeImages": false,
        "consumer_key": "***",
        "consumer_secret": "***",
        "access_token": "***",
        "access_token_secret": "***"
    },
    "sites": [
        "https://shop-usa.palaceskateboards.com/sitemap_products_1.xml",
        "http://kithnyc.com/sitemap_products_1.xml",
        "http://www.socialstatuspgh.com/sitemap_products_1.xml",
        "https://www.laceupnyc.com/sitemap_products_1",
        "https://commonwealth-ftgg.com/sitemap_products_1.xml",
        "https://www.bowsandarrowsberkeley.com/sitemap_products_1.xml",
        "https://xhibition.co/sitemap_products_1.xml",
        "https://cncpts.com/sitemap_products_1.xml",
        "https://www.oneness287.com/sitemap_products_1.xml",
        "https://renarts.com/sitemap_products_1.xml",
        "https://rockcitykicks.com/sitemap_products_1.xml",
        "https://www.featuresneakerboutique.com/sitemap_products_1.xml",
        "https://www.featuresneakerboutique.com/sitemap_products_1.xml",
        "http://www.highsandlows.net.au/sitemap_products_1.xml",
        "https://www.notre-shop.com/sitemap_products_1.xml",
        "https://www.thefactoryokc.com/sitemap_products_1.xml",
        "https://freshragsfl.com/sitemap_products_1.xml",
        "http://wishatl.com/sitemap_products_1.xml",
        "https://www.a-ma-maniere.com/sitemap_products_1.xml",
        "https://www.addictmiami.com/sitemap_products_1.xml",
        "http://attic2zoo.com/sitemap_products_1.xml",
        "https://beatniconline.com/sitemap_products_1.xml",
        "https://www.blendsus.com/sitemap_products_1.xml",
        "http://www.blkmkt.us/sitemap_products_1.xml",
        "https://shop.bdgastore.com/sitemap_products_1.xml",
        "https://burnrubbersneakers.com/sitemap_products_1.xml",
        "http://centre214.com/sitemap_products_1.xml",
        "https://shop.exclucitylife.com/sitemap_products_1.xml",
        "http://shop.extrabutterny.com/sitemap_products_1.xml",
        "http://havenshop.ca/sitemap_products_1.xml",
        "http://www.deadstock.ca/sitemap_products_1.xml",
        "http://www.lapstoneandhammer.com/sitemap_products_1.xml",
        "https://www.minishopmadrid.com/sitemap_products_1.xml",
        "https://nomadshop.net/sitemap_products_1.xml",
        "https://offthehook.ca/sitemap_products_1.xml",
        "https://packershoes.com/sitemap_products_1.xml",
        "https://packershoes.com/sitemap_products_1.xml",
        "https://www.patta.nl/sitemap_products_1.xml",
        "http://www.reigningchamp.com/sitemap_products_1.xml",
        "https://www.rimenyc.com/sitemap_products_1.xml",
        "http://rise45.com/sitemap_products_1.xml",
        "http://rsvpgallery.com/sitemap_products_1.xml",
        "http://shoegallerymiami.com/sitemap_products_1.xml",
        "http://nicekicks.com/sitemap_products_1.xml",
        "http://sneakerpolitics.com/sitemap_products_1.xml",
        "https://www.solefly.com/sitemap_products_1.xml",
        "https://www.soleheaven.com/sitemap_products_1.xml",
        "https://www.ssense.com/sitemap_products_1.xml",
        "http://www.saintalfred.com/sitemap_products_1.xml",
        "https://thepremierstore.com/sitemap_products_1.xml",
        "http://undefeated.com/sitemap_products_1.xml",
        "http://www.uptownmia.com/sitemap_products_1.xml"
    ],
    "keywords": [
        "nmd",
        "ultraboost",
        "ultra-boost",
        "350",
        "consortium",
        "ub-mid",
        "air-jordan",
        "jordan-retro",
        "yeezy",
        "v2"

    ]
}

**Comment by yourfavorite** [comment]
Remove the first line. 'use strict'; That is javascript, not JSON.

**Comment by YeezySzn** [comment]
Lol my bad meant to put that in monitor.js

**Comment by YeezySzn** [comment]
Do you see any syntax error

**Comment by yourfavorite** [comment]
No. Other than being poorly formatted (which shouldn't throw errors), this json is valid. If you are still getting the same error, then I suggest you download the repo again and start over. Try getting it running with a single site before you put in so many sites.

Also, you're trying to run 50 sites with a 1 sec interval. I don't think its going to run very well.

**Comment by YeezySzn** [comment]
Did that got it to run but when I loaded all the sites in got this error.

YzySeason-Macbook-Pro:shopify-monitoryzyseason$ npm start

> shopify-monitor@1.0.0 start /Users/yzyseason/Desktop/shopify-monitor
> node --expose_gc monitor.js

[14:31:17] Local server started on port 1337
[14:31:17] Looking for new items...
[14:31:17] Currently monitoring https://shop-usa.palaceskateboards.com/sitemap_products_1.xml, http://kithnyc.com/sitemap_products_1.xml, https://www.laceupnyc.com/sitemap_products_1, https://commonwealth-ftgg.com/sitemap_products_1.xml, https://www.bowsandarrowsberkeley.com/sitemap_products_1.xml, https://xhibition.co/sitemap_products_1.xml, https://cncpts.com/sitemap_products_1.xml, https://www.oneness287.com/sitemap_products_1.xml, https://renarts.com/sitemap_products_1.xml, https://rockcitykicks.com/sitemap_products_1.xml, https://www.featuresneakerboutique.com/sitemap_products_1.xml, https://www.featuresneakerboutique.com/sitemap_products_1.xml, http://www.highsandlows.net.au/sitemap_products_1.xml, https://www.notre-shop.com/sitemap_products_1.xml, https://www.thefactoryokc.com/sitemap_products_1.xml, https://freshragsfl.com/sitemap_products_1.xml, http://www.wishatl.com/sitemap_products_1.xml, https://www.a-ma-maniere.com/sitemap_products_1.xml, https://www.addictmiami.com/sitemap_products_1.xml, http://attic2zoo.com/sitemap_products_1.xml, https://beatniconline.com/sitemap_products_1.xml, https://www.blendsus.com/sitemap_products_1.xml, http://www.blkmkt.us/sitemap_products_1.xml, https://shop.bdgastore.com/sitemap_products_1.xml, https://burnrubbersneakers.com/sitemap_products_1.xml, http://centre214.com/sitemap_products_1.xml, https://shop.exclucitylife.com/sitemap_products_1.xml, http://shop.extrabutterny.com/sitemap_products_1.xml, http://www.deadstock.ca/sitemap_products_1.xml, http://www.lapstoneandhammer.com/sitemap_products_1.xml, https://www.minishopmadrid.com/sitemap_products_1.xml, https://nomadshop.net/sitemap_products_1.xml, https://offthehook.ca/sitemap_products_1.xml, https://packershoes.com/sitemap_products_1.xml, https://packershoes.com/sitemap_products_1.xml, https://www.patta.nl/sitemap.xml, http://www.reigningchamp.com/sitemap_products_1.xml, https://www.rimenyc.com/sitemap_products_1.xml, http://rise45.com/sitemap_products_1.xml, http://rsvpgallery.com/sitemap_products_1.xml, http://shoegallerymiami.com/sitemap_products_1.xml, http://sneakerpolitics.com/sitemap_products_1.xml, https://www.solefly.com/sitemap_products_1.xml, https://www.soleheaven.com/sitemap_products_1.xml, https://www.ssense.com/sitemap_products_1.xml, http://www.saintalfred.com/sitemap_products_1.xml, https://thepremierstore.com/sitemap_products_1.xml, http://www.uptownmia.com/sitemap_products_1.xml and http://www.socialstatuspgh.com/sitemap_products_1.xml
[14:31:17] Twitter service is currently enabled.
[14:31:17] Getting initial data...
[14:31:17] Interval set for every 60000ms
events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'length' of undefined
    at /Users/yzyseason/Desktop/shopify-monitor/lib/index.js:179:41
    at Parser.<anonymous> (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at SAXParser.onclosetag (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
    at SAXParser.write (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/node_modules/sax/lib/sax.js:1452:13)
    at Parser.exports.Parser.Parser.parseString (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/Users/yzyseason/Desktop/shopify-monitor/node_modules/xml2js/lib/xml2js.js:540:19)
    at Request._callback (/Users/yzyseason/Desktop/shopify-monitor/lib/index.js:163:9)
    at Request.self.callback (/Users/yzyseason/Desktop/shopify-monitor/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! shopify-monitor@1.0.0 start: `node --expose_gc monitor.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-monitor@1.0.0 start script 'node --expose_gc monitor.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shopify-monitor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --expose_gc monitor.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shopify-monitor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shopify-monitor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yzyseason/Desktop/shopify-monitor/npm-debug.log

**Comment by YeezySzn** [comment]
Cut the sites in half and it works flawlessly

**Comment by yourfavorite** [comment]
Glad you got it working. Please close the issue.

**Comment by YeezySzn** [comment]
Welp stopped working

**Comment by YeezySzn** [comment]
Got this it was running and after a tweet got this
<img width="223" alt="screen shot 2017-03-20 at 6 40 32 pm" src="https://cloud.githubusercontent.com/assets/19716029/24128987/d0f8dab4-0d9c-11e7-8320-c460973fe4ed.png">

**Comment by OddOsprey** [comment]
That is a manual garbage clean^ Not an error

**Comment by KalebHolley** [comment]
I'm getting a connection error
Connection Error @ https://kithnyc.com, polling again in 300000ms
