### ISSUE TITLE
index line 31 error

### ISSUE THREAD

**Issue by yzygang** [dzt/shopify-monitor#46]
for (var i = 0; i < jsonBodyProduct.product.variants.length; i++) {
                                                       ^

TypeError: Cannot read property 'variants' of undefined

this happens only when I have Keywords set to true

**Comment by yzygang** [comment]
100 sitemaps and using 300,000 interval

**Comment by yzygang** [comment]
C:\Users\Administrator\desktop\keywordmonitor\lib\index.js:31
            for (var i = 0; i < jsonBodyProduct.product.variants.length; i++) {
                                                                               ^

TypeError: Cannot read property 'variants' of undefined
    at Request._callback (C:\Users\Administrator\desktop\keywordmonitor\lib\index.js:31:56)
    at Request.self.callback (C:\Users\Administrator\desktop\keywordmonitor\node_modules\request\
request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Administrator\desktop\keywordmonitor\node_modules\request\re
quest.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\desktop\keywordmonitor\node_modules\re
quest\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by cameronb23** [comment]
Version 2 has been released with many bug fixes and an overall revamp of codebase - please attempt on version 2 and reopen if your issue still arises, or create a new one if a different bug appears.
