### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by dpas0** [dzt/shopify-monitor#48]
after the inital check i get this error,

C:\Users\Daniel\shopify-monitor-master\lib\index.js:31
            for (var i = 0; i < jsonBodyProduct.product.variants.length; i++) {
                                                       ^

TypeError: Cannot read property 'variants' of undefined
    at Request._callback (C:\Users\Daniel\shopify-monitor-master\lib\index.js:31:56)
    at Request.self.callback (C:\Users\Daniel\shopify-monitor-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (C:\Users\Daniel\shopify-monitor-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (C:\Users\Daniel\shopify-monitor-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Thanks

**Comment by dpas0** [comment]
seems to work if i have a very short sitemap list. would still like any suggestions how to fix it when using more sitemaps

**Comment by cameronb23** [comment]
Version 2 has been released with many bug fixes and an overall revamp of codebase - please attempt on version 2 and reopen if your issue still arises, or create a new one if a different bug appears.
