### ISSUE TITLE
Errors when running on windows server from mac

### ISSUE THREAD

**Issue by ajshaffer** [dzt/shopify-monitor#83]
It run's the initial check for each website then it throws this:
I'm running 44 websites and changed the 300000 to 600000 in the config.json

Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:287:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) sql: undefined, bindings: undefined }
[Sun Nov 12 2017 15:05:49] [LOG]   err { TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full.
Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:287:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) sql: undefined, bindings: undefined }
[Sun Nov 12 2017 15:05:49] [LOG]   err { TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full.
Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:287:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) sql: undefined, bindings: undefined }
[Sun Nov 12 2017 15:05:50] [LOG]   err { TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full.
Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:287:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) sql: undefined, bindings: undefined }
C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\bluebird\js\release\using.js:12
        setTimeout(function(){throw e;}, 0);
                              ^

RangeError: Maximum call stack size exceeded
    at Object.log (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:232:24)
    at Pool.log [as _log] (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib\generic-p
ool.js:168:19)
    at Pool.dispense [as _dispense] (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib
\generic-pool.js:300:10)
    at Pool._addResourceToAvailableObjects (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-p
ool\lib\generic-pool.js:396:8)
    at Pool.release (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib\generic-pool.js
:470:8)
    at C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:295:23
    at Pool.dispense [as _dispense] (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib
\generic-pool.js:310:12)
    at Pool._addResourceToAvailableObjects (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-p
ool\lib\generic-pool.js:396:8)
    at Pool.release (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib\generic-pool.js
:470:8)
    at C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:295:23
    at Pool.dispense [as _dispense] (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib
\generic-pool.js:310:12)
    at Pool._addResourceToAvailableObjects (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-p
ool\lib\generic-pool.js:396:8)
    at Pool.release (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib\generic-pool.js
:470:8)
    at C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:295:23
    at Pool.dispense [as _dispense] (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib
\generic-pool.js:310:12)
    at Pool._addResourceToAvailableObjects (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-p
ool\lib\generic-pool.js:396:8)
    at Pool.release (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib\generic-pool.js
:470:8)
    at C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:295:23
    at Pool.dispense [as _dispense] (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib
\generic-pool.js:310:12)
    at Pool._addResourceToAvailableObjects (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-p
ool\lib\generic-pool.js:396:8)
    at Pool.release (C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\generic-pool\lib\generic-pool.js
:470:8)
    at C:\Users\Administrator\desktop\shopify-monitor-master\node_modules\knex\lib\client.js:295:23
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor-2@2.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopify-monitor-2@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-12T15_05_51_991Z-debug.log
PS C:\Users\Administrator\desktop\shopify-monitor-master> RangeError: Maximum call stack size exceeded

**Comment by dzt** [comment]
Do you have the acquireConnectionTimeout field in the database object in the config.json file set to 600000 or higher?

**Comment by ajshaffer** [comment]
Yes I also changed that to 600000

**Comment by XioYang23** [comment]
Blocked the previous issue comment wasnt assuming ....actually 
If you input proxies say any mount 200 300 500 100 proxies what ever 
and run the script your just going to get proxies count value , and a bunch of parsing errors
& then
If you go on a shopify website thru your IP your temp banned ....but should nt the requests be handled by the proxies ? Of course 60000 is going to work as that is minutes late and under the shopify bann rate if you lower to say 20000 30000 your temp banned on ur IP , if you check the proxies there arent banned.....because hmmm proxies arent being used So please dont use "view the source" as a reasoning or excuse because you can write anything dont mean its actually being used or dont get offended when issues are brought up

**Comment by cameronb23** [comment]
@XioYang23 [here](https://github.com/dzt/shopify-monitor/blob/master/service.js#L56) is what you are looking for. It blatantly specifies proxy in the request configuration. I just checked all the codebase and the only place requesting without a proxy is when (A) you are sending discord/slack notification or (B) in the `lib/index` file, which is not used. Please do not create issues / reply to issues unless it is a _real_ bug. Thank you.

**Comment by XioYang23** [comment]
Ive tested your script along against a another one :
Two different servers (which i monthly keep running) proxies count 150 each total of 300.
After changing your default ms because as it comes already late on tasks 
I also came across parsing errors immediately upon start 
Gave it 15mins break : Restarted immediately parsing error
Went to the websites which where giving me parsing error &
TEMP BANNED found it weird because im not running anything on shopify that should indeed capture my IP lol okay : waited for the temp banned unblocked: reran :
maybe two websites worked then parsing error : went to the webpages from chrome 
TEMP BANNED : ive set your rules true proxies and whats needed , It captures my total proxie 
count but does not indeed use as a request module . I can be doing something wrong but your 
wecome to run the steps above and again i didnt start this issue thread im mainly adding on to the issue at hand .

**Comment by cameronb23** [comment]
@XioYang23 All issues have been fixed for any proxy problems anyone would be having. If you really need help please DM me on [twitter](https://twitter.com/cgalt23).

**Comment by XioYang23** [comment]
Ur welcome
