### ISSUE TITLE
npm error on mac

### ISSUE THREAD

**Issue by kfinest** [dzt/shopify-monitor#85]
MacBook-Air:shopify-monitor Kenny$ npm start

> shopify-monitor-2@2.0.0 start /Users/Kenny/shopify-monitor
> babel-node index.js

module.js:538
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Kenny/shopify-monitor/index.js:12:16)
    at Module._compile (module.js:635:30)
    at loader (/Users/Kenny/shopify-monitor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Kenny/shopify-monitor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at Object.<anonymous> (/Users/Kenny/shopify-monitor/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor-2@2.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-monitor-2@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /Users/Kenny/.config │
└──────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Kenny/.npm/_logs/2017-11-15T20_26_34_523Z-debug.log
MacBook-Air:shopify-monitor Kenny$

**Comment by cameronb23** [comment]
You need to rename the default configuration to `config.json` instead of `config.example.json` when using the monitor. Feel free to re-open the issue if this isn't the case / didn't fix your problem.
