### ISSUE TITLE
Connection error to every site even with 1000000 Conn delay

### ISSUE THREAD

**Issue by ajshaffer** [dzt/shopify-monitor#90]
I'm getting a connection error to every site. My settings are:
"pollTimeMs": 1000000,
    "proxies": false,
    "slackBot": {
        "active": true,
        "token": "xxxxxxxxxxxxxxxxx",
        "channel": "monitor",
        "settings": {
            "username": "shopifymonitor",
            "icon_url": "https://i.imgur.com/E0BubGr.png"
        }
    },
    "discord": {
      "active": false,
      "webhook_url": "url here"
    },
    "twitter": {
        "active": true,
        "encodeImages": false,
        "consumer_key": "xxxxxx",
        "consumer_secret": "xxxxxxxxxxx",
        "access_token": "xxxxxxxx",
        "access_token_secret": "xxxxxxxxxx"
    },
    "database": {
        "client": "sqlite3",
        "connection": {
            "filename": "./monitor-database.sqlite3"
        },
        "acquireConnectionTimeout": 1000000,
        "useNullAsDefault": true

**Comment by skycorrigan** [comment]
I'm having the same problem. I've tried various poll times and also different variations of sites (kith.com vs kith's sitemap) but to no avail.

**Comment by Johnwall719** [comment]
Exactly I was having the same problem and ended up getting blocked by the developer because they didn't understand how to develop., I showed the developer a screenshot of my config where acquire connection was set to 60,000 and I think he ignored it because a couple hours later he commented on the closed issue saying the solution is to change the config to 60,000. https://github.com/dzt/shopify-monitor/issues/72 But the truth is I did some research. Changing the config to 60000 makes NO change to the issue at all.

See I researched the database library they are using. It's knex. It says in the documentation that the default value for acquireConnectionTimeout is already 60000 from the start. http://knexjs.org/#Installation-acquireConnectionTimeout "acquireConnectionTimeout defaults to 60000ms". So the real problem in shopify-monitor is that the devs did not properly program the way shopify uses the database. I couldn't figure out because I'm not a javascript developer but the error does say "The pool is probably full. Are you missing a .transacting(trx) call?" A database pool works by having a set number of connections and the code must temporarily use a connection then put it back in the pool. If it's saying the pool is full, that means the code in shopify is opening database connections without ever closing them. Also I searched the entire code for something that looks like " .transacting(trx)" and I couldn't find anything. Something is clearly wrong and the knex is not being used properly.

**Comment by skycorrigan** [comment]
No transacting(trx) errors here, from what I can see. Only the connection errors. Hopefully the dev(s) will see this soon.

**Comment by ajshaffer** [comment]
Yeah i think with all the updating the devs are doing, it's not a finished product just yet. Everything loads up and works besides the connection errors.

**Comment by skycorrigan** [comment]
What I've done to get things going for now was dropped down to v2.0. Hopefully a resolution to the connection errors will come out later.

**Comment by cameronb23** [comment]
Connection errors are exactly what they seem. They mean that there was a problem connecting to the website. This means one of a few things:
- you have a problem with your internet
- you have a problem with proxies
- the site is unavailable(down)
Parsing errors, however, can mean a few things. Either the response data is malformed(failed to retrieve data correctly), or you are banned.

A transaction call, as I'm told, is due to not enough resources(memory?)

If any of you have any more questions, please feel free to DM me @cgalt23 on twitter.

**Comment by Johnwall719** [comment]
ajshaffer skycorrigan 
u guys got anything that i can contact u guys with? discord? twitter?

**Comment by ajshaffer** [comment]
Follow my Twitter @bigburrtha

On Nov 23, 2017, at 3:16 AM, Johnwall719 <notifications@github.com<mailto:notifications@github.com>> wrote:


ajshaffer skycorrigan
u guys got anything that i can contact u guys with? discord? twitter?

**Comment by bennt1** [comment]
Make sure you clean out the proxy file. I found even with proxy set to false, the program was loading up the text in proxy file and using it to connect. All was well after clearing out the proxy.txt file saving and restarting.

**Comment by skycorrigan** [comment]
@bennt1 Thank you for the tip! It was exactly the fix that I needed. I just wish that I knew of it earlier as I checked out every file in the program, except this one, for something that seemed out of place.

**Comment by bennt1** [comment]
glad I could help, I was driven to the edge too!

**Comment by Johnwall719** [comment]
My config:

"database": {
        "client": "sqlite3",
        "connection": {
            "filename": "./monitor-database.sqlite3"
        },
        "acquireConnectionTimeout": 700000,
        "useNullAsDefault": true
    },


Errors:

[Sun Nov 19 2017 19:22:39] [LOG]   err { TimeoutError: Knex: Timeout acquiring a
 connection. The pool is probably full. Are you missing a .transacting(trx) call
?
    at Timeout._onTimeout (\shopify\node_modules\kn
ex\lib\client.js:287:18)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) sql: undefined, bindings: undefined
 }
I was instructioned by this software's developer to increase acquireConnectionTimeout but it didn't help solve this error I'm receiving. does anyone know how the error can be fixed?

I'm no export at javascript or knex but perhaps the program isn't closing its database connections and the pool is becoming full of opened connections?

**Comment by skycorrigan** [comment]
@Johnwall719 Could you post your whole config? That way I can compare it against mine. Also, did you clear out your proxies.txt file (if you're not using proxies) as mentioned by @bennt1?

**Comment by Johnwall719** [comment]
My config:

"database": {
        "client": "sqlite3",
        "connection": {
            "filename": "./monitor-database.sqlite3"
        },
        "acquireConnectionTimeout": 700000,
        "useNullAsDefault": true
    },


Errors:

[Sun Nov 19 2017 19:22:39] [LOG]   err { TimeoutError: Knex: Timeout acquiring a
 connection. The pool is probably full. Are you missing a .transacting(trx) call
?
    at Timeout._onTimeout (\shopify\node_modules\kn
ex\lib\client.js:287:18)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) sql: undefined, bindings: undefined
 }
I was instructioned by this software's developer to increase acquireConnectionTimeout but it didn't help solve this error I'm receiving. does anyone know how the error can be fixed?

**Comment by Johnwall719** [comment]
@skycorrigan

**Comment by Johnwall719** [comment]
I'm no export at javascript or knex but perhaps the program isn't closing its database connections and the pool is becoming full of opened connections?

**Comment by Johnwall719** [comment]
@skycorrigan  u got any contacts?

**Comment by bennt1** [comment]
Just an idea,

Maybe try adding the debug switch to your config.json ?
It just might add some more detailed error messages to the log. It looks
like your not binding at all.


 "database": {
        "client": "sqlite3",
        "debug": "true",
        "connection": {
            "filename": "./monitor-database.sqlite3"
        },
        "acquireConnectionTimeout":600000,
        "useNullAsDefault": true
    },


also check your sqlite install with something like  npm-check. it will show
the installed module versions.

$ npm install -g npm-check

<https://www.npmjs.com/package/npm-check#use>Use

$ npm-check


just my 2cents.

I would be happy to teamview in to your machine if you want to screen
share.

-jason

**Comment by skycorrigan** [comment]
@Johnwall719 No contacts on social media. I just have my email. 

Couple of questions:
1) What's your OS?
2) Have you tried the install in a virtual machine (VM)?

If after trying @bennt1 suggestions, I'd recommend doing the install in a VM so that you have a fresh baseline w/o any possible conflicting software.

**Comment by trvpbo0om** [comment]
im having the same problem guys and there no text in my proxy.txts other than what the dev wrong as an example

**Comment by trvpbo0om** [comment]
ACGDeptordsiMac:shopify-monitor acgdeptford$ npm start

> shopify-monitor-2@2.0.0 start /Users/acgdeptford/Desktop/shopify-monitor
> babel-node index.js

[Fri Dec 29 2017 16:19:53] [LOG]   [ 'host:port:username:password',
  'or',
  'host:port',
  'line by line' ]
[Fri Dec 29 2017 16:19:53] [LOG]   ------------------------------------------------
[Fri Dec 29 2017 16:19:53] [LOG]                  ShopifyMonitor v2
[Fri Dec 29 2017 16:19:53] [LOG]   ------------------------------------------------
[Fri Dec 29 2017 16:19:53] [LOG]                   Developed by dzt
[Fri Dec 29 2017 16:19:53] [LOG]   ------------------------------------------------
[Fri Dec 29 2017 16:19:53] [LOG]   config.json file has been loaded
[Fri Dec 29 2017 16:19:54] [LOG]   Starting Tasks...
[Fri Dec 29 2017 16:19:54] [LOG]   All tasks have been successfully Initialized
[Fri Dec 29 2017 16:19:54] [LOG]   ------------------------------------------------
[Fri Dec 29 2017 16:19:54] [LOG]   Slack Bot Enabled
[Fri Dec 29 2017 16:19:54] [LOG]   Discord Bot Enabled
[Fri Dec 29 2017 16:19:54] [LOG]   ------------------------------------------------
[Fri Dec 29 2017 16:19:54] [LOG]   Connection Error @ https://fuckingawesomestore.com, polling again in 300000ms
[Fri Dec 29 2017 16:19:54] [LOG]   Connection Error @ https://fuckthepopulation.com, polling again in 300000ms
[Fri Dec 29 2017 16:19:54] [LOG]   Connection Error @ https://shop.dertbag.us, polling again in 300000ms
[Fri Dec 29 2017 16:19:54] [LOG]   Connection Error @ https://store.illegalcivilization.com, polling again in 300000ms
[Fri Dec 29 2017 16:19:54] [LOG]   Connection Error @ https://offthehook.ca, polling again in 300000ms
ect.....

**Comment by Johnwall719** [comment]
@skycorrigan provide me with your email

**Comment by camron114** [comment]
so i had got it to run a few times but now nothing 
this is all im getting an nothing in is out putting in my slack or discord now 



[Sat Dec 30 2017 02:01:08] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:01:08] [LOG]                  ShopifyMonitor v2
[Sat Dec 30 2017 02:01:08] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:01:08] [LOG]                   Developed by dzt
[Sat Dec 30 2017 02:01:08] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:01:08] [LOG]   config.json file has been loaded
[Sat Dec 30 2017 02:01:08] [LOG]   Unable to parse proxy
[Sat Dec 30 2017 02:01:08] [LOG]   Proxies: 36
[Sat Dec 30 2017 02:01:08] [LOG]   Site Count: 22
[Sat Dec 30 2017 02:01:08] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:01:09] [LOG]   Starting Tasks...
[Sat Dec 30 2017 02:01:09] [LOG]   All tasks have been successfully Initialized
[Sat Dec 30 2017 02:01:09] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:01:09] [LOG]   Slack Bot Enabled
[Sat Dec 30 2017 02:01:09] [LOG]   Discord Bot Enabled
[Sat Dec 30 2017 02:01:09] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:01:09] [LOG]   Connection Error @ https://lapstoneandhammer.                                                                                                                           com, polling again in 100000ms
[Sat Dec 30 2017 02:01:17] [LOG]   Initial Check (Successful):  shop.extrabutter                                                                                                                           ny.com
[Sat Dec 30 2017 02:01:24] [LOG]   Initial Check (Successful):  shop.exclucityli                                                                                                                           fe.com
[Sat Dec 30 2017 02:01:25] [LOG]   Initial Check (Successful):  shop.dertbag.us
[Sat Dec 30 2017 02:01:26] [LOG]   Initial Check (Successful):  shop-usa.palaces                                                                                                                           kateboards.com
[Sat Dec 30 2017 02:01:26] [LOG]   Initial Check (Successful):  beatniconline.co                                                                                                                           m
[Sat Dec 30 2017 02:01:29] [LOG]   Initial Check (Successful):  saintalfred.com
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://fuckthepopulation.                                                                                                                           com, polling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://fuckingawesomestor                                                                                                                           e.com, polling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://xhibition.co, poll                                                                                                                           ing again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://kith.com, polling                                                                                                                            again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://offthehook.ca, pol                                                                                                                           ling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://rsvpgallery.com, p                                                                                                                           olling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://burnrubbersneakers                                                                                                                           .com, polling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://wishatl.com, polli                                                                                                                           ng again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://notre-shop.com, po                                                                                                                           lling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://store.illegalcivil                                                                                                                           ization.com, polling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://commonwealth-ftgg.                                                                                                                           com, polling again in 100000ms
[Sat Dec 30 2017 02:01:30] [LOG]   Connection Error @ https://socialstatuspgh.co                                                                                                                           m, polling again in 100000ms
[Sat Dec 30 2017 02:01:50] [LOG]   Initial Check (Successful):  shop.bdgastore.c                                                                                                                           om
[Sat Dec 30 2017 02:01:50] [LOG]   Connection Error @ https://rockcitykicks.com,                                                                                                                            polling again in 100000ms

**Comment by camron114** [comment]
i got it to work a few time but now this is all im getting 
the only out put im getting now Shopify Monitor currently active ◕‿◕ in my slack 
                                                                                                                   
[Sat Dec 30 2017 02:14:25] [LOG]   config.json file has been loaded
[Sat Dec 30 2017 02:14:25] [LOG]   Unable to parse proxy
[Sat Dec 30 2017 02:14:26] [LOG]   Starting Tasks...
[Sat Dec 30 2017 02:14:26] [LOG]   All tasks have been successfully Initialized
[Sat Dec 30 2017 02:14:26] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:14:26] [LOG]   Slack Bot Enabled
[Sat Dec 30 2017 02:14:26] [LOG]   Discord Bot Enabled
[Sat Dec 30 2017 02:14:26] [LOG]   ---------------------------------------------                                                                                                                           ---
[Sat Dec 30 2017 02:14:27] [LOG]   Initial Check (Successful):  fuckthepopulatio                                                                                                                           n.com
[Sat Dec 30 2017 02:14:28] [LOG]   Initial Check (Successful):  store.illegalciv                                                                                                                           ilization.com
[Sat Dec 30 2017 02:14:30] [LOG]   Initial Check (Successful):  fuckingawesomest                                                                                                                           ore.com
[Sat Dec 30 2017 02:14:30] [LOG]   Initial Check (Successful):  shop.dertbag.us
[Sat Dec 30 2017 02:14:32] [LOG]   Initial Check (Successful):  shop-usa.palaces                                                                                                                           kateboards.com
[Sat Dec 30 2017 02:14:36] [LOG]   Initial Check (Successful):  shop.extrabutter                                                                                                                           ny.com
[Sat Dec 30 2017 02:14:41] [LOG]   Initial Check (Successful):  rockcitykicks.co                                                                                                                           m
[Sat Dec 30 2017 02:14:42] [LOG]   Initial Check (Successful):  beatniconline.co                                                                                                                           m
[Sat Dec 30 2017 02:14:46] [LOG]   Initial Check (Successful):  offthehook.ca
[Sat Dec 30 2017 02:15:02] [LOG]   Initial Check (Successful):  shop.bdgastore.c                                                                                                                           om
[Sat Dec 30 2017 02:15:04] [LOG]   Initial Check (Successful):  notre-shop.com
[Sat Dec 30 2017 02:15:09] [LOG]   Initial Check (Successful):  sneakerpolitics.                                                                                                                           com
[Sat Dec 30 2017 02:15:13] [LOG]   Initial Check (Successful):  wishatl.com
[Sat Dec 30 2017 02:15:18] [LOG]   Initial Check (Successful):  shop.exclucityli                                                                                                                           fe.com
[Sat Dec 30 2017 02:15:19] [LOG]   Initial Check (Successful):  burnrubbersneake                                                                                                                           rs.com
[Sat Dec 30 2017 02:15:21] [LOG]   Initial Check (Successful):  xhibition.co
[Sat Dec 30 2017 02:15:30] [LOG]   Initial Check (Successful):  kith.com
[Sat Dec 30 2017 02:15:34] [LOG]   Initial Check (Successful):  socialstatuspgh.                                                                                                                           com
[Sat Dec 30 2017 02:15:35] [LOG]   Initial Check (Successful):  saintalfred.com
[Sat Dec 30 2017 02:15:40] [LOG]   Initial Check (Successful):  lapstoneandhamme                                                                                                                           r.com
[Sat Dec 30 2017 02:15:43] [LOG]   Initial Check (Successful):  rsvpgallery.com
[Sat Dec 30 2017 02:15:49] [LOG]   Initial Check (Successful):  commonwealth-ftg                                                                                                                           g.com

**Comment by Johnwall719** [comment]
@cameronb23  RIP

**Comment by skycorrigan** [comment]
@trvpbo0om, the proxies.txt file should be empty if you're not using proxies. Meaning, delete the proxy example lines from the file. Save. Then restart.

**Comment by trvpbo0om** [comment]
thank. im kind of mad my problem wasn't more complicated lol

**Comment by skycorrigan** [comment]
@trvpbo0om You're welcome

**Comment by Johnwall719** [comment]
@sky Corrigan can we teamview?

**Comment by Johnwall719** [comment]
@skycorrigan *

**Comment by camron114** [comment]
[Sat Dec 30 2017 17:18:11] [LOG]   []
[Sat Dec 30 2017 17:18:11] [LOG]   ------------------------------------------------
[Sat Dec 30 2017 17:18:11] [LOG]                  ShopifyMonitor v2
[Sat Dec 30 2017 17:18:11] [LOG]   ------------------------------------------------
[Sat Dec 30 2017 17:18:11] [LOG]                   Developed by dzt
[Sat Dec 30 2017 17:18:11] [LOG]   ------------------------------------------------
[Sat Dec 30 2017 17:18:11] [LOG]   config.json file has been loaded
[Sat Dec 30 2017 17:18:12] [LOG]   Starting Tasks...
[Sat Dec 30 2017 17:18:12] [LOG]   All tasks have been successfully Initialized
[Sat Dec 30 2017 17:18:12] [LOG]   ------------------------------------------------
[Sat Dec 30 2017 17:18:12] [LOG]   Slack Bot Enabled
[Sat Dec 30 2017 17:18:12] [LOG]   Discord Bot Enabled
[Sat Dec 30 2017 17:18:12] [LOG]   ------------------------------------------------
[Sat Dec 30 2017 17:18:12] [LOG]   Initial Check (Successful):  fuckthepopulation.com
[Sat Dec 30 2017 17:18:13] [LOG]   Initial Check (Successful):  fuckingawesomestore.com
[Sat Dec 30 2017 17:18:14] [LOG]   Initial Check (Successful):  store.illegalcivilization.com
[Sat Dec 30 2017 17:18:15] [LOG]   Initial Check (Successful):  beatniconline.com
[Sat Dec 30 2017 17:18:22] [LOG]   Initial Check (Successful):  sneakerpolitics.com
[Sat Dec 30 2017 17:18:23] [LOG]   Initial Check (Successful):  shop.dertbag.us
[Sat Dec 30 2017 17:18:27] [LOG]   Initial Check (Successful):  offthehook.ca
[Sat Dec 30 2017 17:18:32] [LOG]   Initial Check (Successful):  commonwealth-ftgg.com
[Sat Dec 30 2017 17:18:33] [LOG]   Initial Check (Successful):  trophyroomstore.com
[Sat Dec 30 2017 17:18:38] [LOG]   Initial Check (Successful):  rockcitykicks.com
[Sat Dec 30 2017 17:18:40] [LOG]   Initial Check (Successful):  rsvpgallery.com
[Sat Dec 30 2017 17:18:45] [LOG]   Initial Check (Successful):  shop.extrabutterny.com
[Sat Dec 30 2017 17:18:47] [LOG]   Initial Check (Successful):  saintalfred.com
[Sat Dec 30 2017 17:18:47] [LOG]   Initial Check (Successful):  shop-usa.palaceskateboards.com
[Sat Dec 30 2017 17:18:52] [LOG]   Initial Check (Successful):  lapstoneandhammer.com
[Sat Dec 30 2017 17:18:56] [LOG]   Initial Check (Successful):  shop.exclucitylife.com
[Sat Dec 30 2017 17:19:00] [LOG]   Initial Check (Successful):  wishatl.com
[Sat Dec 30 2017 17:19:02] [LOG]   Initial Check (Successful):  xhibition.co
[Sat Dec 30 2017 17:19:04] [LOG]   Initial Check (Successful):  notre-shop.com
[Sat Dec 30 2017 17:19:12] [LOG]   Initial Check (Successful):  kith.com
[Sat Dec 30 2017 17:19:14] [LOG]   Initial Check (Successful):  burnrubbersneakers.com
[Sat Dec 30 2017 17:19:18] [LOG]   Initial Check (Successful):  socialstatuspgh.com
[Sat Dec 30 2017 17:19:32] [LOG]   Initial Check (Successful):  shopnicekicks.com
[Sat Dec 30 2017 17:19:49] [LOG]   Initial Check (Successful):  shop.bdgastore.com


please let me know what im doing wrong  
can we get a update to fix the error we having ?
been running this all day an still nothing :-1:

**Comment by skycorrigan** [comment]
We can. Pass me your TeamViewer ID and I'll connect in.
  

  
  

  
  
>

**Comment by skycorrigan** [comment]
@Johnwall719 skycorrigan@gmail.com

**Comment by skycorrigan** [comment]
@camron114 If you're timezone is EST, then from your log it looks like you just started the program and it's running correctly. Do remember that the program will only provide output when new and/or restock items from your site and keyword list are detected. Give it time; the program works.

If you want to test it to see it in action, put some generic keywords (think Nike, Adidas, etc) in your config.json file, save, and restart.

**Comment by Johnwall719** [comment]
So all this time I'm showing a database error and I'm getting ignored by the dev and being told it's a connection error when clearly @trvpbo0om  just showed the connection error which is a completely different error and mine is:

```
[Sun Nov 19 2017 19:22:39] [LOG] err { TimeoutError: Knex: Timeout acquiring a
connection. The pool is probably full. Are you missing a .transacting(trx) call
?
at Timeout._onTimeout (\shopify\node_modules\kn
ex\lib\client.js:287:18)
at ontimeout (timers.js:386:11)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5) sql: undefined, bindings: undefined
}

trvpbo0om:
```
`[Fri Dec 29 2017 16:19:54] [LOG] Connection Error @ https://fuckingawesomestore.com, polling again in 300000ms`

Just to completely clarify it is a database error I am encountering.

I ran npm-check and it reported this for sqlite3 :
```
sqlite3      ?  NOTUSED?  Still using sqlite3?                                                            Depcheck did not find code similar to require('sqlite3') or import from 'sqlite3'.                                                    
```

Also it told me my knex was outdated so I updated it from v12 to v14 maybe that will do the trick.

**Comment by camron114** [comment]
thank u so much i got it now  @skycorrigan

**Comment by LoremIpsum1** [comment]
Hey guys Im still having a problem even after reading this, so I cleared proxies.txt and left it empty and I get this: 


[Mon Jan 01 2018 20:01:13] [LOG]   Slack Bot Enabled
[Mon Jan 01 2018 20:01:13] [LOG]   Discord Bot Enabled
[Mon Jan 01 2018 20:01:13] [LOG]   ------------------------------------------------
[Mon Jan 01 2018 20:01:13] [LOG]   Connection Error @ https://www.store.illegalcivilization.com, polling again in 300000ms
[Mon Jan 01 2018 20:01:14] [LOG]   Initial Check (Successful):  https://www.fuckthepopulation.com

it seems to stop there..

and sometimes I get this, both come up randomly: 

[Mon Jan 01 2018 20:05:55] [LOG]                   Developed by dzt
[Mon Jan 01 2018 20:05:55] [LOG]   ---------------------------------------------                                                                                                                                                             ---
[Mon Jan 01 2018 20:05:56] [LOG]   config.json file has been loaded
[Mon Jan 01 2018 20:05:56] [ASSERT][Mon Jan 01 2018 20:05:57] [WARN]  Unhandled                                                                                                                                                              rejection Error: SQLITE_BUSY: database is locked
[Mon Jan 01 2018 20:05:57] [LOG]   err { Error: SQLITE_BUSY: database is locked                                                                                                                                                              errno: 5, code: 'SQLITE_BUSY' }

Any idea?

**Comment by camron114** [comment]
img: 'https://cdn.shopify.com/s/files/1/0049/9112/products/IMG_2554_2.png?v=1401217959',
  price: '$256.00' }
[Tue Jan 02 2018 01:50:21] [LOG]   { title: 'NIKE TECH FLEECE',
  handle: 'tech-fleece-pant',
  stock: 0,
  status: 'Sold Out',
  links:
   [ { baseUrl: 'https://shop.bdgastore.com',
       id: 939328417,
       title: 'Black [011]' },
     { baseUrl: 'https://shop.bdgastore.com',
       id: 13827586820,
       title: 'Black [011]' } ],
  img: 'https://cdn.shopify.com/s/files/1/0049/9112/products/Nike-Tech-Fleece-Pant-blk.jpg?v=1410538891',
  price: '$100.00' }
[Tue Jan 02 2018 01:50:21] [LOG]   { title: 'Flyknit Max',
  handle: 'flyknit-max-1',
  stock: 0,
  status: 'Sold Out',
  links:
   [ { baseUrl: 'https://shop.bdgastore.com',
       id: 735595713,
       title: 'Bright Crimson [600]' } ],
  img: 'https://cdn.shopify.com/s/files/1/0049/9112/products/IMG_0831_01525b33-deb2-4577-994e-20e3d6e743ca.jpg?v=1399654266',
  price: '$225.00' }
[Tue Jan 02 2018 01:50:21] [LOG]   { title: 'Alert Watch Cap',
  handle: 'alert-watch-cap',
  stock: 0,
  status: 'Sold Out',
  links:
   [ { baseUrl: 'https://shop.bdgastore.com',
       id: 980489180,
       title: 'Marled Purple' } ],
  img: 'https://cdn.shopify.com/s/files/1/0049/9112/products/Raised-By-Wolves-ALERT_WATCH_CAP_PRPL_BLCK.jpg?v=1413491276',
  price: '$25.00' }
[Tue Jan 02 2018 01:50:21] [LOG]   { title: 'October',
  handle: 'october',
  stock: 0,
  status: 'Sold Out',
  links:
   [ { baseUrl: 'https://shop.bdgastore.com',
       id: 1022076112,
       title: 'Black' } ],
  img: 'https://cdn.shopify.com/s/files/1/0049/9112/products/Nixon-October-_blk.jpg?v=1416420455',

so im picking up items but its not out putting in my slack or discord  ?

**Comment by LoremIpsum1** [comment]
@camron114 

Make sure you check config.json to make sure your slackbot key is correct under "token" :

  "pollTimeMs": 300000,
    "proxies": false,
    "slackBot": {
        "active": true,
        "token": "xoxb-292114648xxx-634789500xx",
        "channel": "shopify-monitor",
        "settings": {
            "username": "Monitor",
            "icon_url": "https://i.imgur.com/E0BubGr.png"
