### ISSUE TITLE
not sure what this means but help me please boss

### ISSUE THREAD

**Issue by joshszn** [dzt/shopify-monitor#92]
SyntaxError: C:\Users\Josh\shopify-monitor\config.json: Unexpected token ] in JSON at position 1151
    at JSON.parse ()
    at Object.Module._extensions..json (module.js:654:27)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object. (C:/Users/Josh/shopify-monitor/index.js:12:16)
    at Module._compile (module.js:635:30)
    at loader (C:\Users\Josh\shopify-monitor\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Josh\shopify-monitor\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object. (C:\Users\Josh\shopify-monitor\app.js:2:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
CODE LINES
cannot retrieve source context

**Comment by esl753** [comment]
ya i got same error after i updated this morning... not sure what it is

**Comment by cameronb23** [comment]
invalid configuration. dm me on twitter @cgalt23 and ill see what's wrong.
